### PR TITLE
#167484601 Pagination support for articles

### PR DESCRIPTION
**Pull request by malaba6**
### What does this PR do?
- Adds pagination functionality when the user is retreiving articles

### Description of Task to be completed?
- Add two query parameters in on the getArticles route and specify the page number and the record limit
- Change the sequelize query to contain the offset and limit value for the paginated result

### How should this be manually tested?
In Postman or Swagger or any other tool of your choice visit these endpoints:
*POST*`/api/v1/articles?page=XXXX&limit=XXXX` to fetch all articles with the specified pagination

### What are the relevant pivotal tracker stories?
[Pagination support for articles](https://www.pivotaltracker.com/story/show/#167484601)

###Any background context you want to provide?
User this environment variable `ARTICLE_URL=http://localhost:3000/api/v1/articles`

### Screenshots? 
*In Postman*
Screen Shot 2019-08-27 at 13 37 08

### CODE REVIEW

**Review by raymond42 — CHANGES_REQUESTED** [review]
1. Why should I be able to retrieve the articles when I put the page which has a negative number and limit as well?
2. In the response body, If there is a way you could add page number it could be better

**Comment by malaba6** [comment]
> * Why should I be able to retrieve the articles when I put the page which has a negative number and limit as well?
> * In the response body, If there is a way you could add page number it could be better

> @raymond42 about retrieving articles when the page and limit values are invalid, I made it in such a way that if the value is invalid, the default value applies, which is `page 1` and `limit 10`
> About the page number, I made the change, thanx!

**Review by Jkadhuwa — APPROVED** [review]
Looks good

**Review by harerakalex — APPROVED** [review]
Looks good

**Review by mkiterian — APPROVED** [review]

**Pull request merged**
