### PR TITLE
#167484576 configure eslint and add eslint dependencies

### PR DESCRIPTION
**Pull request by harerakalex**
### What does this PR do?
- ESlint configuration
### Description of Task to be completed?
- Create .eslintrc.json file and add configuration
- Add three dependencies that are related to eslint
### How should this be manually tested?
- Right now, you can pull this branch and then try to write some line of code, so the eslint will start to give some rules to be followed.
### Any background context you want to provide?
- N/A
### What are the relevant pivotal tracker stories?
- [Configure ESLint](https://www.pivotaltracker.com/story/show/167484576)
### Questions
- N/A

### CODE REVIEW

**Review by raymond42 — CHANGES_REQUESTED** [review]
You can change depemdencies to dependencies on the PR title and also add story id on the beginning of the PR title

**Review by Jkadhuwa — CHANGES_REQUESTED** [review]
Nice work, but could you reduce the indentation to like 2 tabs in .eslintrc.json file.

**Comment by harerakalex** [comment]
@Jkadhuwa, Check this is what I have locally.
Screen Shot 2019-07-31 at 08 28 34

**Comment by Jkadhuwa** [comment]
> @Jkadhuwa, Check this what I have locally.
> Screen Shot 2019-07-31 at 08 28 34

Looks good.

**Review by Jkadhuwa — APPROVED** [review]

**Review by raymond42 — APPROVED** [review]

**Review by mkiterian — APPROVED** [review]

**Pull request merged**
