### PR TITLE
#167484589 implemented social login

### PR DESCRIPTION
**Pull request by placideirandora**
#### What does this PR do?
It implements the approach of being able to login with social network platforms such as Google, Twitter, and Facebook.

#### Description of Task to be done?
1. Adding routes for social login with Google, Twitter, or Facebook.
2. Adding callback routes for storing profile information from social platforms.
3. Adding tests for the social login routes and controllers.

#### Screenshots
Screen Shot 2019-08-17 at 20 41 50
Screen Shot 2019-08-17 at 20 42 07
Screen Shot 2019-08-17 at 20 42 19

#### How should this be manually tested?
1. Clone this branch.
2. Don **npm install**.
3. Add values to these variables in your **.env** file:
FACEBOOK_APP_ID=
FACEBOOK_APP_SECRET=
GOOGLE_APP_ID=
GOOGLE_APP_SECRET=
TWITTER_APP_KEY=
TWITTER_APP_SECRET=
TWITTER_TOKEN=
TWITTER_TOKEN_SECRET=
4. Log into your Gmail, Twitter, and Facebook accounts for being able to test the social login feature.
5. Then, visit corresponding social login routes for each platform, Google, Twitter, and Facebook:
localhost:3000/api/v1/auth/google, localhost:3000/api/v1/auth/twitter/, and localhost:3000/api/v1/auth/facebook, with your browser.
6. Authorize **Authors Haven** app to access to your account.
7. Check if you get a message telling you that you have logged in with your preferred platform.

### CODE REVIEW

**Review by Jkadhuwa — COMMENTED** [review]
I get that error when I try logging in with Twitter.

Screen Shot 2019-08-19 at 09 57 06

**Review by raymond42 — CHANGES_REQUESTED** [review]
check if the user is successfully logged in, verification to be turned to true

**Comment by placideirandora** [comment]
> I get that error when I try logging in with Twitter.
> 
> Screen Shot 2019-08-19 at 09 57 06

Check the user model to see if the userName is allowed to be unique and if it is... Remove that rule.

**Comment by placideirandora** [comment]
> check if the user is successfully logged in, verification to be turned to true

Okay!

**Comment by placideirandora** [comment]
> I get that error when I try logging in with Twitter.
> 
> Screen Shot 2019-08-19 at 09 57 06

Check the user model to see if the userName is allowed to be unique and if it is... Remove that rule.

**Comment by Jkadhuwa** [comment]
> > I get that error when I try logging in with Twitter.
> > Screen Shot 2019-08-19 at 09 57 06
> 
> Check the user model to see if the userName is allowed to be unique and if it is... Remove that rule.

But if we remove the rule users could end up having the same userName which is not ideal

**Review by malaba6 — COMMENTED** [review]
It looks good, only that social facebook login is not working for now. And your tests are failing on Travis, are you sure all the environment variables have been added?

**Review by harerakalex — COMMENTED** [review]
Facebook login is not working.

**Comment by placideirandora** [comment]
> It looks good, only that social facebook login is not working for now. And your tests are failing on Travis, are you sure all the environment variables have been added?

Go straight to Travis and run re-run the test of this branch and they will pass.

**Review by malaba6 — COMMENTED** [review]
Test coverage has dropped alarmingly when I run it locally. Can you fix these red lines?
Screen Shot 2019-08-19 at 11 44 01

**Comment by placideirandora** [comment]
> Facebook login is not working.

The Facebook policy requires the app to be hosted on a real server such as Heroku. So, after the deployment, you test it. But now, I'm using it for development purpose only.

**Comment by placideirandora** [comment]
> Test coverage has dropped alarmingly when I run it locally. Can you fix these red lines?
> Screen Shot 2019-08-19 at 11 44 01

You should check this: https://travis-ci.org/andela/coding-geeks-ah-backend/builds/573203822

**Comment by placideirandora** [comment]
> Test coverage has dropped alarmingly when I run it locally. Can you fix these red lines?
> Screen Shot 2019-08-19 at 11 44 01

Yeah, I'm working on how to cover those lines!

**Comment by placideirandora** [comment]
> > > I get that error when I try logging in with Twitter.
> > > Screen Shot 2019-08-19 at 09 57 06
> > 
> > 
> > Check the user model to see if the userName is allowed to be unique and if it is... Remove that rule.
> 
> But if we remove the rule users could end up having the same userName which is not ideal

For the social login, the user will have the same username regardless of the platform used. For instance, the same user can have different usernames according to a platform used (google, twitter, or facebook). And that's not ideal because we want to track the user. Therefore, that's why on social login, the same user can have the same username across all their social platforms.

**Comment by placideirandora** [comment]
> check if the user is successfully logged in, verification to be turned to true

I have implemented your feedback!

**Review by raymond42 — APPROVED** [review]

**Pull request merged**
